### ISSUE TITLE
Is .math needed?

### ISSUE THREAD

**Issue by ken-morel** [K1DV5/tkinter-math#4]
Hello! 
Looking gain pour readme and learning more about your docal seems my issues and pulls going some too extra to the initial modules objective, is that the case ? 
And should I build a personal project and use as dependency?
Thanks!

**Comment by K1DV5** [comment]
Hello there, it is not the initial objective but the reason I built this lib separately is for the possibility of someone else finding another use case for it. So I am actually in support of expanding it, I will review and accept the pull request. Thank you.

And yes, you can do what you like with it as well.
